name: Auto Create and Merge PR

on:
  workflow_dispatch:
    branches:
      - development

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:

    - name: ğŸ›  Setup gh
      run: |
        echo ${{secrets.PAT}} | gh auth login --with-token

    - name: ğŸ›’ Checkout code
      uses: actions/checkout@v3
      with:
        ref: development

    - name: ğŸ•µï¸ Check for changes
      id: check_changes
      run: |
        git fetch origin main:main
        changes=$(git diff --name-only main..development)

        if [ -z "$changes" ]; then
          echo "No changes detected. Exiting."
          echo "::set-output name=changes::failiure"
          exit 0
        fi

## TODO: DIFFERENT WORKFLOW FOR EMAILS

    - name: ğŸ“§ Send Email
      if: ${{ steps.check_changes.outputs.changes != '' }}
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          from: Wrappid Care
          to: ${{secrets.IDS}}
          cc: ${{secrets.MAINTAINER_ID}}
          subject: ${{ github.event.repository.name }} - No new commits since the last publish.
          body: |
            Hi Wrappid Managers,

            There were no new commits since the last publish in ${{ github.event.repository.name }} package repository as of ${{ steps.date.outputs.date }}.
            
            Thank you for your attention and cooperation.

            Thanks and Regards,
            wrappidcare

            generated by Github Action Workflow

## NOT GETTING PR URL

    - name: ğŸ“¤ Create PR
      run: |
        pr_url=$(gh pr create --base main --head development --title "Automated PR" --body "Automated PR created by GitHub Actions." | awk '/created/ {print $5}')
        echo "PR URL: $pr_url"

    - name: ğŸ”€ Merge PR
      run: |
        pr_number=$(echo $pr_url | cut -d '/' -f 7)
        gh pr merge $pr_number --admin --rebase
