name: Publish Package

on:
  workflow_dispatch:
    branches:
      - development
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed
  repository_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    # Runs this job if workflow_dispatch event occurs or if workflow run event is success
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout...
        uses: actions/checkout@v3
      
      - name: get release
        run: |
          gh release download --pattern '*.tgz'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/wrappid
          token: ${{secrets.PUBLISH_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path:  ${{ github.event.repository.name }}
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN}}
    
      - name: Publish Release
        run: npm run publish

      - name: Extract version
        id: extract_version
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            secure: true
            from: Wrappid Care
            to: ${{secrets.IDS}}
            cc: ${{secrets.MAINTAINER_ID}}
            subject: Published - ${{ matrix.repo_names }} - ${{ steps.extract_version.outputs.version }} Package. ðŸš€
            html_body: |
              <html lang="en">

              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Exciting News from Wrappiders</title>
              </head>

              <body>
                <p>Hi Wrappiders,</p>

                <p>We have some exciting news to share with you! ðŸŽ‰<br>
                  We have published a new version of our ${{ github.event.repository.name }}, ${{ steps.extract_version.outputs.version }}. ðŸš€<br>
                  This version comes with some amazing new features and improvements that will make your experience with our package even better.
                  You can check out the details on our <a href="https://github.com/wrappid/${{ github.event.repository.name }}/releases/latest">${{ github.event.repository.name }} page</a>.
                </p>

                <p>We hope you enjoy using our framework, and we would love to hear your feedback.
                  Please feel free to <a href="mailto:wrappid.framework@gmail.com">contact us</a> if you have any questions or suggestions.
                </p>

                <p>Thank you for your continued support and trust in us. ðŸ˜Š</p>

                <p>Thanks and Regards,<br>
                  ${{github.actor}}<br>
                  (Generated by the fast-publish GitHub Action workflow)</p>
              </body>

              </html>
            ignore_cert: true
            convert_markdown: true
            # attachments: attachments.zip,git.diff
            priority: normal